# Generated by Django 3.1.8 on 2022-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_on_comment',
            field=models.ManyToManyField(related_name='comments_liked', to='logreg.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes_on_messages',
            field=models.ManyToManyField(related_name='messages_liked', to='logreg.User'),
        ),
    ]
